### ISSUE TITLE
Final UI Design

### ISSUE THREAD

**Issue by mar-cas3** [ISIS3510-202410-Team23/Backend#57]
Design System
- [x] Color palette
- [x] Fonts
- [x] Shared / Standard Components (Logos, images, ...)

**Comment by juanyepesp** [comment]
@nklopstock611 @JuanCamFalla @Alejandro1400 
please revise prototype and close this issue; remember to adapt this prototype to materialUI for android

https://www.figma.com/file/iDL2L3f5ZJNcNygtHanP5y/Prototype-FoodBook?type=design&node-id=1%3A5&mode=design&t=uo2cYsdvYrwP1IWa-1
