### ISSUE TITLE
[FIX] Migrate backend deployment from fl0 to alternatives

### ISSUE THREAD

**Issue by mar-cas3** [ISIS3510-202410-Team23/Backend#83]
fl0 will be shutting down on May 4th so we need to migrate deployment to another service. @nklopstock611 please leave in a comment possible alternatives.

**Comment by nklopstock611** [comment]
Possible alternatives:
- https://render.com/
- https://railway.app/
- https://fly.io/

**Comment by nklopstock611** [comment]
I made the migration to https://render.com/, here is the new URL: https://foodbook-app-backend.onrender.com/

**Comment by juanyepesp** [comment]
Cool, thanks!
